{% set version = "4.1.1.post1" %}

package:
  name: pykeepass
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pykeepass/pykeepass-{{ version }}.tar.gz
  sha256: 28f4927454ebe507ef7294d3ec6b5a72ee3a5c97fcc21b1080b8ddc09f2097dd

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ={{ python_min }}
    - setuptools >=59.0.0
    - pip
  run:
    - python >={{ python_min }}
    - pyotp >=2.9.0
    - construct >=2.10.53
    - argon2-cffi >=18.1.0
    - pycryptodomex >=3.6.2
    - lxml

test:
  commands:
    - pip check
  imports:
    - pykeepass
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/libkeepass/pykeepass
  summary: Python library to interact with keepass databases (supports KDBX3 and KDBX4)
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
