schema_version: 1

context:
  version: "4.2.0"

package:
  name: pykeepass
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pykeepass/pykeepass-${{ version }}.tar.gz
  sha256: 0e40eabdac19a511a2be4e550984cbf01f1fd8ec9d9055456136fab266e5cc66

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python =${{ python_min }}
    - setuptools >=59.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - pyotp >=2.9.0
    - construct >=2.10.53
    - argon2-cffi >=18.1.0
    - pycryptodomex >=3.6.2
    - lxml

tests:
  - python:
      imports:
        - pykeepass
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  summary: Python library to interact with keepass databases (supports KDBX3 and KDBX4)
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/libkeepass/pykeepass

extra:
  recipe-maintainers:
    - danielnachun
